# Generated by Django 2.2.5 on 2020-01-30 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Core_committee',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('team', models.CharField(max_length=255)),
                ('pic', models.ImageField(upload_to='images/team')),
                ('position', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
