# Generated by Django 2.2.5 on 2020-01-30 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='core_committee',
            old_name='team',
            new_name='post',
        ),
    ]
