# Generated by Django 2.2.5 on 2020-01-30 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company_name', models.CharField(max_length=255)),
                ('about_company', models.TextField()),
                ('job_description', models.TextField()),
                ('role', models.CharField(max_length=255)),
                ('job_requirement', models.TextField()),
                ('mandatory_skills', models.TextField()),
                ('stipend', models.IntegerField()),
                ('Company_url', models.URLField()),
                ('Company_age', models.IntegerField()),
                ('loctaion', models.TextField()),
                ('perks', models.TextField()),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('logo', models.ImageField(upload_to='images/intern_fair')),
            ],
        ),
    ]
